location = /cantantes-de-salsa {
    return 301 https://prensa.lavozsalsa.com/cantantes-de-salsa/$is_args$args;
}

location = /cantantes-de-salsa/ {
    return 301 https://prensa.lavozsalsa.com/cantantes-de-salsa/$is_args$args;
}

location = /exitos-de-la-salsa-romantica {
    return 301 https://prensa.lavozsalsa.com/exitos-de-la-salsa-romantica/$is_args$args;
}

location = /exitos-de-la-salsa-romantica/ {
    return 301 https://prensa.lavozsalsa.com/exitos-de-la-salsa-romantica/$is_args$args;
}

location = /descargar-salsa {
    return 301 https://prensa.lavozsalsa.com/descargar-salsa/$is_args$args;
}

location = /descargar-salsa/ {
    return 301 https://prensa.lavozsalsa.com/descargar-salsa/$is_args$args;
}

location = /salsa-baul {
    return 301 https://prensa.lavozsalsa.com/salsa-baul/$is_args$args;
}

location = /salsa-baul/ {
    return 301 https://prensa.lavozsalsa.com/salsa-baul/$is_args$args;
}

location = /adolescentes-orquesta-la-historia-verdadera-de-porfi-baloa {
    return 301 https://prensa.lavozsalsa.com/adolescentes-orquesta-la-historia-verdadera-de-porfi-baloa/$is_args$args;
}

location = /adolescentes-orquesta-la-historia-verdadera-de-porfi-baloa/ {
    return 301 https://prensa.lavozsalsa.com/adolescentes-orquesta-la-historia-verdadera-de-porfi-baloa/$is_args$args;
}

location = /bares-salsa-medellin {
    return 301 https://prensa.lavozsalsa.com/bares-salsa-medellin/$is_args$args;
}

location = /bares-salsa-medellin/ {
    return 301 https://prensa.lavozsalsa.com/bares-salsa-medellin/$is_args$args;
}

location = /frankie-ruiz-el-papa-de-la-salsa {
    return 301 https://prensa.lavozsalsa.com/frankie-ruiz-el-papa-de-la-salsa/$is_args$args;
}

location = /frankie-ruiz-el-papa-de-la-salsa/ {
    return 301 https://prensa.lavozsalsa.com/frankie-ruiz-el-papa-de-la-salsa/$is_args$args;
}

location = /yo-me-llamo-frankie-ruiz {
    return 301 https://prensa.lavozsalsa.com/yo-me-llamo-frankie-ruiz/$is_args$args;
}

location = /yo-me-llamo-frankie-ruiz/ {
    return 301 https://prensa.lavozsalsa.com/yo-me-llamo-frankie-ruiz/$is_args$args;
}

location = /david-zahan-y-frankie-ruiz-reviviendo-al-papa-de-la-salsa {
    return 301 https://prensa.lavozsalsa.com/david-zahan-y-frankie-ruiz-reviviendo-al-papa-de-la-salsa/$is_args$args;
}

location = /david-zahan-y-frankie-ruiz-reviviendo-al-papa-de-la-salsa/ {
    return 301 https://prensa.lavozsalsa.com/david-zahan-y-frankie-ruiz-reviviendo-al-papa-de-la-salsa/$is_args$args;
}

location = /mimi-ibarra-cantautora {
    return 301 https://prensa.lavozsalsa.com/mimi-ibarra-cantautora/$is_args$args;
}

location = /mimi-ibarra-cantautora/ {
    return 301 https://prensa.lavozsalsa.com/mimi-ibarra-cantautora/$is_args$args;
}

location = /internacional-grupo-gale-toda-una-historia-musical {
    return 301 https://prensa.lavozsalsa.com/internacional-grupo-gale-toda-una-historia-musical/$is_args$args;
}

location = /internacional-grupo-gale-toda-una-historia-musical/ {
    return 301 https://prensa.lavozsalsa.com/internacional-grupo-gale-toda-una-historia-musical/$is_args$args;
}

location = /tito-rojas {
    return 301 https://prensa.lavozsalsa.com/tito-rojas/$is_args$args;
}

location = /tito-rojas/ {
    return 301 https://prensa.lavozsalsa.com/tito-rojas/$is_args$args;
}
