location = /tv {
    return 301 https://app.lavozsalsa.com/tv$is_args$args;
}

location = /tv/ {
    return 301 https://app.lavozsalsa.com/tv$is_args$args;
}

location = /pulso-salsero {
    return 301 https://prensa.lavozsalsa.com/$is_args$args;
}

location = /pulso-salsero/ {
    return 301 https://prensa.lavozsalsa.com/$is_args$args;
}

location = /blog {
    return 301 https://prensa.lavozsalsa.com/$is_args$args;
}

location = /blog/ {
    return 301 https://prensa.lavozsalsa.com/$is_args$args;
}

location = /explorar/musica {
    return 301 https://lavozsalsa.com/;
}

location = /explorar/musica/ {
    return 301 https://lavozsalsa.com/;
}

location = /explorar/radio {
    return 301 https://app.lavozsalsa.com/tv$is_args$args;
}

location = /explorar/radio/ {
    return 301 https://app.lavozsalsa.com/tv$is_args$args;
}

location = /explorar/playlist {
    return 301 https://prensa.lavozsalsa.com/$is_args$args;
}

location = /explorar/playlist/ {
    return 301 https://prensa.lavozsalsa.com/$is_args$args;
}
